/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    programs: Program;
    categories: Category;
    activities: Activity;
    'committee-members': CommitteeMember;
    'membership-registrations': MembershipRegistration;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'committee-members': CommitteeMembersSelect<false> | CommitteeMembersSelect<true>;
    'membership-registrations': MembershipRegistrationsSelect<false> | MembershipRegistrationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ms') | ('en' | 'ms')[];
  globals: {
    'home-hero': HomeHero;
    'home-editorial': HomeEditorial;
    'home-showcase': HomeShowcase;
    'home-impact': HomeImpact;
    'programs-ui': ProgramsUi;
    'home-activities': HomeActivity;
    'home-footer': HomeFooter;
    'about-page': AboutPage;
    'gallery-ui': GalleryUi;
    'contact-page': ContactPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'home-editorial': HomeEditorialSelect<false> | HomeEditorialSelect<true>;
    'home-showcase': HomeShowcaseSelect<false> | HomeShowcaseSelect<true>;
    'home-impact': HomeImpactSelect<false> | HomeImpactSelect<true>;
    'programs-ui': ProgramsUiSelect<false> | ProgramsUiSelect<true>;
    'home-activities': HomeActivitiesSelect<false> | HomeActivitiesSelect<true>;
    'home-footer': HomeFooterSelect<false> | HomeFooterSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'gallery-ui': GalleryUiSelect<false> | GalleryUiSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'ms';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Home → upcoming sessions in the programs table
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  _order?: string | null;
  title: string;
  details?: string | null;
  category: 'team' | 'racket' | 'fitness' | 'aquatic' | 'outdoor' | 'youth';
  venue: string;
  start: string;
  end: string;
  image: number | Media;
  /**
   * Optional muted loop for richer program cards/previews (not required for the Upcoming Programs table).
   */
  video?: (number | null) | Media;
  /**
   * Attached images for this program (works like the Activities album photos field).
   */
  photos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images and videos used across the site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Activity categories — also power the Active Life collage images on the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  _order?: string | null;
  title: string;
  image: number | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Activities with category, media, and photo album — used on home + /gallery
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  _order?: string | null;
  /**
   * URL path under /gallery/[slug]
   */
  slug: string;
  title: string;
  /**
   * Pick from Categories collection
   */
  category: number | Category;
  summary?: string | null;
  description?: string | null;
  /**
   * Shown on the gallery album page
   */
  date?: string | null;
  venue?: string | null;
  /**
   * Homepage card + gallery cover
   */
  image: number | Media;
  /**
   * Optional muted loop on the homepage activity card
   */
  video?: (number | null) | Media;
  /**
   * Gallery album photos for this activity (replaces separate albums)
   */
  photos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Position in the Activities stage pair
   */
  slot: 'topLeft' | 'bottomRight';
  pair: 'pair-a' | 'pair-b';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * About page → organization chart
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee-members".
 */
export interface CommitteeMember {
  id: number;
  name: string;
  role: string;
  image: number | Media;
  order?: number | null;
  social?: {
    twitter?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
    behance?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * New member sign-ups from /membership — filter by sport to see registrants per activity
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-registrations".
 */
export interface MembershipRegistration {
  id: number;
  fullName: string;
  email: string;
  /**
   * Format: XXXXXX-XX-XXXX
   */
  icNumber: string;
  phone: string;
  /**
   * Main sport preference from the registration form
   */
  sport: 'football' | 'archery' | 'tableTennis' | 'badminton' | 'others';
  photo?: (number | null) | Media;
  addressLine: string;
  address: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in to the CMS
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'committee-members';
        value: number | CommitteeMember;
      } | null)
    | ({
        relationTo: 'membership-registrations';
        value: number | MembershipRegistration;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  details?: T;
  category?: T;
  venue?: T;
  start?: T;
  end?: T;
  image?: T;
  video?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  _order?: T;
  slug?: T;
  title?: T;
  category?: T;
  summary?: T;
  description?: T;
  date?: T;
  venue?: T;
  image?: T;
  video?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  slot?: T;
  pair?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee-members_select".
 */
export interface CommitteeMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  order?: T;
  social?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        instagram?: T;
        behance?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-registrations_select".
 */
export interface MembershipRegistrationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  icNumber?: T;
  phone?: T;
  sport?: T;
  photo?: T;
  addressLine?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Top of homepage — shutter carousel, title text, and partners marquee
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  /**
   * Word repeated across the yellow shutter bars (e.g. PSR).
   */
  title: string;
  /**
   * One indicator per slide. Cycle: still image → video (file wins over YouTube ID).
   */
  slides?:
    | {
        /**
         * Shown in the first half of this slide’s indicator cycle (also used as video poster).
         */
        image: number | Media;
        alt: string;
        /**
         * Optional. Plays muted & looped in the second half of this slide. Takes priority over YouTube ID.
         */
        video?: (number | null) | Media;
        /**
         * Optional fallback when no video file is uploaded. e.g. L3374C3OyrY from youtu.be/L3374C3OyrY.
         */
        youtubeId?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small eyebrow above the logo marquee (e.g. Partners).
   */
  partnersLabel?: string | null;
  /**
   * Logos in the infinite strip under the hero. Leave empty to use the default files in /images/hero/Partners.
   */
  partners?:
    | {
        logo: number | Media;
        name: string;
        /**
         * Optional. Opens when the logo is clicked.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Home → TRAIN / COMPETE / EVOLVE stepped block
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-editorial".
 */
export interface HomeEditorial {
  id: number;
  /**
   * e.g. TRAIN
   */
  topText: string;
  /**
   * e.g. COMPETE
   */
  middleText: string;
  /**
   * e.g. EVOLVE
   */
  bottomText: string;
  /**
   * e.g. Push forward
   */
  overlayText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Home → Active Life brand copy. Collage images come from Categories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-showcase".
 */
export interface HomeShowcase {
  id: number;
  brandLine1: string;
  brandLine2: string;
  brandAmp: string;
  brandLine3: string;
  script: string;
  tagline: string;
  viewMore?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Home → Sports Strong / scroll impact visuals
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-impact".
 */
export interface HomeImpact {
  id: number;
  lineA: string;
  lineB: string;
  scriptA: string;
  scriptB: string;
  background?: (number | null) | Media;
  floatLeft?: (number | null) | Media;
  floatRight?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Home → Programs table titles, filters, and buttons
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs-ui".
 */
export interface ProgramsUi {
  id: number;
  title: string;
  subtitle?: string | null;
  empty?: string | null;
  join?: string | null;
  joinNow?: string | null;
  close?: string | null;
  viewAll?: string | null;
  showLess?: string | null;
  filters?: {
    all?: string | null;
    team?: string | null;
    racket?: string | null;
    fitness?: string | null;
    aquatic?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Home → Activities title, description, and Join the Movement
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-activities".
 */
export interface HomeActivity {
  id: number;
  title: string;
  description?: string | null;
  membership?: {
    titleLine1?: string | null;
    titleLine2?: string | null;
    description?: string | null;
    joinCta?: string | null;
    imageAlt?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Social circles and bottom legal bar (copy in code for now)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-footer".
 */
export interface HomeFooter {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * About page → hero, story, mission, pillars, and CTA
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  eyebrow?: string | null;
  title: string;
  lead?: string | null;
  heroImage?: (number | null) | Media;
  storyTitle?: string | null;
  story?: string | null;
  storyImage?: (number | null) | Media;
  missionTitle?: string | null;
  mission?: string | null;
  visionTitle?: string | null;
  vision?: string | null;
  committeeTitle?: string | null;
  committeeSubtitle?: string | null;
  pillarsTitle?: string | null;
  pillars?:
    | {
        key: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaBody?: string | null;
  ctaMembership?: string | null;
  ctaActivities?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Gallery page → titles and button labels
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-ui".
 */
export interface GalleryUi {
  id: number;
  title: string;
  subtitle?: string | null;
  viewAlbum?: string | null;
  backToGallery?: string | null;
  photosHeading?: string | null;
  photoCount?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact page → hero, details, and form labels
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  eyebrow?: string | null;
  title: string;
  lead?: string | null;
  detailsTitle?: string | null;
  detailsLead?: string | null;
  imageAlt?: string | null;
  image?: (number | null) | Media;
  form?: {
    title?: string | null;
    subtitle?: string | null;
    name?: string | null;
    namePlaceholder?: string | null;
    email?: string | null;
    emailPlaceholder?: string | null;
    phone?: string | null;
    phonePlaceholder?: string | null;
    subject?: string | null;
    subjectPlaceholder?: string | null;
    message?: string | null;
    messagePlaceholder?: string | null;
    submit?: string | null;
    submitting?: string | null;
    note?: string | null;
    successTitle?: string | null;
    successBody?: string | null;
    sendAnother?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Shared site name, contact details, and hours
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name?: string | null;
  description?: string | null;
  email?: string | null;
  phoneDisplay?: string | null;
  phoneTel?: string | null;
  whatsappDisplay?: string | null;
  whatsappDigits?: string | null;
  addressLines?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  hours?:
    | {
        days: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  title?: T;
  slides?:
    | T
    | {
        image?: T;
        alt?: T;
        video?: T;
        youtubeId?: T;
        id?: T;
      };
  partnersLabel?: T;
  partners?:
    | T
    | {
        logo?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-editorial_select".
 */
export interface HomeEditorialSelect<T extends boolean = true> {
  topText?: T;
  middleText?: T;
  bottomText?: T;
  overlayText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-showcase_select".
 */
export interface HomeShowcaseSelect<T extends boolean = true> {
  brandLine1?: T;
  brandLine2?: T;
  brandAmp?: T;
  brandLine3?: T;
  script?: T;
  tagline?: T;
  viewMore?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-impact_select".
 */
export interface HomeImpactSelect<T extends boolean = true> {
  lineA?: T;
  lineB?: T;
  scriptA?: T;
  scriptB?: T;
  background?: T;
  floatLeft?: T;
  floatRight?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs-ui_select".
 */
export interface ProgramsUiSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  empty?: T;
  join?: T;
  joinNow?: T;
  close?: T;
  viewAll?: T;
  showLess?: T;
  filters?:
    | T
    | {
        all?: T;
        team?: T;
        racket?: T;
        fitness?: T;
        aquatic?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-activities_select".
 */
export interface HomeActivitiesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  membership?:
    | T
    | {
        titleLine1?: T;
        titleLine2?: T;
        description?: T;
        joinCta?: T;
        imageAlt?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-footer_select".
 */
export interface HomeFooterSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  heroImage?: T;
  storyTitle?: T;
  story?: T;
  storyImage?: T;
  missionTitle?: T;
  mission?: T;
  visionTitle?: T;
  vision?: T;
  committeeTitle?: T;
  committeeSubtitle?: T;
  pillarsTitle?: T;
  pillars?:
    | T
    | {
        key?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaBody?: T;
  ctaMembership?: T;
  ctaActivities?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-ui_select".
 */
export interface GalleryUiSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  viewAlbum?: T;
  backToGallery?: T;
  photosHeading?: T;
  photoCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  detailsTitle?: T;
  detailsLead?: T;
  imageAlt?: T;
  image?: T;
  form?:
    | T
    | {
        title?: T;
        subtitle?: T;
        name?: T;
        namePlaceholder?: T;
        email?: T;
        emailPlaceholder?: T;
        phone?: T;
        phonePlaceholder?: T;
        subject?: T;
        subjectPlaceholder?: T;
        message?: T;
        messagePlaceholder?: T;
        submit?: T;
        submitting?: T;
        note?: T;
        successTitle?: T;
        successBody?: T;
        sendAnother?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  email?: T;
  phoneDisplay?: T;
  phoneTel?: T;
  whatsappDisplay?: T;
  whatsappDigits?: T;
  addressLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  hours?:
    | T
    | {
        days?: T;
        time?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}